### ISSUE TITLE
0.4.0 Game freeze when open settings tab

### ISSUE THREAD

**Issue by Gillwindy** [hitsub/CookieAssistant#11]
only CCSE and CookieAssistant mod applied.

https://user-images.githubusercontent.com/3596447/133099340-1a6e91e6-3b76-4476-a6b5-23873196eb15.mp4

**Comment by hitsub** [comment]
@Gillwindy 
Thx reporting!
Can you give me the full save data (with mod data) when this bug happened?

**Comment by hitsub** [comment]
May have entered the options before the Pantheon has finished loading, and the list of spirits is no longer loading.

**Comment by Seefour** [comment]
> May have entered the options before the Pantheon has finished loading, and the list of spirits is no longer loading.

How long am I supposed to wait until entering the settings panel?

**Comment by hitsub** [comment]
I found that if go into the options with an account before unlocked Pantheon, game got frozen.
Fixed in 0.4.2, so wait a moment.
