### ISSUE TITLE
Click on big cookie if "Click Frenzy" buff is on

### ISSUE THREAD

**Issue by lkotlarenko** [hitsub/CookieAssistant#21]
Idea / suggestion
It would be nice to have an option on AutoClick BigCookie to click only if "Click Frenzy" buff is on

**Comment by lkotlarenko** [comment]
Great! Thank you :smile:

**Comment by hitsub** [comment]
実装予定のモード:
・常時
・何らかのバフ(1つ以上)
・何らかのバフ(2つ以上)
・クリックバフ(ClickFrenzy or DragonFlight)
