### ISSUE TITLE
Add "Preserve Shiny Wrinklers" mode to Auto-click wrinkler feature

### ISSUE THREAD

**Issue by fortunymaxim** [hitsub/CookieAssistant#37]
Could you replace your wrinkler popper line of code with this so that the shiny ones are preserved?

Game.wrinklers.forEach(function(me){ if (me.close==1 && wrinkler.type !== 1) me.hp = 0});

**Comment by hitsub** [comment]
I forgot to do that. Thanks!
I'll implement to get it toggled.

**Comment by fortunymaxim** [comment]
Also so sorry I'm a dumbass, wrinkler.type should be me.type, but I'm sure you already spotted it. Thanks for making this incredibly useful mod!!
