### ISSUE TITLE
Error upon opening options menu

### ISSUE THREAD

**Issue by jennyl** [hitsub/CookieAssistant#56]
0.6.0

![image](https://user-images.githubusercontent.com/4051215/134814652-a047bd2a-27bc-448f-8d61-fe33194438a2.png)

**Comment by hitsub** [comment]
@jennyl 
Thanks for reporting, let me ask you a few questions.

1. Did this error occur in an update from 0.5.0?
2. Just get an error? Or does the game freeze?
3. Because I can't reproduce it, could you give me your save data?

**Comment by jennyl** [comment]
hi

I was upgrading from 0.4
The game didn't freeze, the mod just failed to load.

sorry, I already deleted my save data. 
But deleting the data and re-enabling the mod worked. 

So, it was because I edited `main.js`, which saved my custom data in my save file, and then the new version tried to load my old save file which led to undefined errors.
