### ISSUE TITLE
Add an option to limit golden cookie auto clicking when you get a Cookie Storm

### ISSUE THREAD

**Issue by cheatfreak47** [hitsub/CookieAssistant#64]
As it is, automatic golden cookie click can click an inhuman amount of the golden cookies at a time when you get a Cookie Storm, resulting in absurdly large gains when getting that golden cookie outcome.

It would be nice if there were an option to limit the number of golden cookies you click when a cookie storm happens, so that it still behaves close to human-like in terms of gains. 

Maybe just make it able to only click one golden cookie on screen at once, and it has to wait the interval period before clicking the next one?

**Comment by hitsub** [comment]
Thanks for your opinion, but there is no motivation to implement that.

- Cookie Storm only has a 3% chance of occurring
- It event doesn't earn much cookies
(e.g. Combining Frenzy with auto click big cookie will produce a much larger amount of cookies than Cookie Storm)

Therefore, I think that the disadvantage of making the option even more complicated is greater than merit of implement that.

**Comment by cheatfreak47** [comment]
fair enough, I just thought it seemed to be a bit of an unfair advantage over normal human play
great work on the add-on btw, very useful :)
