### ISSUE TITLE
allow setting interval period for the action to perform after autosell

### ISSUE THREAD

**Issue by cheatfreak47** [hitsub/CookieAssistant#79]
the auto sell change in 7.0 made it so it now waits the autosell interval before trying to buy back buildings, and then sells them again after it hits it again....

This means you can no longer sell and instantly buy back your buildings, instead you'd need to set it to 5s (5000ms) or more so it just so happens to work out mathematically. This kind of sucks because it means half the time you lose the CPS from the buildings you sold

instead, the interval setting for auto sell should be specifically auto sell only, and then we should have a second interval for how long to wait after selling before we perform the second action (usually buy back)

an example of how this should work:
```
AutoSell Buildings On: [Inverval 10010ms (~10-seconds)]
   Sell Cursors for 830 when Always
       Do After Activated: Buy Back the Amount Sold [Interval 200ms (~1/5sec)
```
in this example, this would mean, every 10010ms it would try to auto sell the amount of buildings
and then, 200ms after the sell action, it would try to buy the amount sold back

instead as of now, I have to do this to achieve the closest to the same result
```
AutoSell Buildings On: [Inverval 5020ms (~5-seconds)]
   Sell Cursors for 830 when Always
       Do After Activated: Buy Back the Amount Sold 
```
which results in every 5020ms it either sells buildings OR buys them back depending on what it did previously, and every devastation buff, I lose all the extra cursor CPS for half of the buff time :(

**Comment by hitsub** [comment]
Sorry, I can't understand the meaning of what you wrote.

> This means you can no longer sell and instantly buy back your buildings, instead you'd need to set it to 5s (5000ms) or more so it just so happens to work out mathematically. This kind of sucks because it means half the time you lose the CPS from the buildings you sold

The auto sell feature works even if the interval is set to 1ms.

This works:
1. sell the building
2. buy back them
3. wait interval time
4. return to number 1

This works very powerfully to get the Godzamok buff.
What is the problem?

**Comment by hitsub** [comment]
Ok, I understand your point probably. Thanks for the explanation.

The reason why some Interval settings are hidden is because I think they are unnecessary, and the button to show them is for people who have edited with the values in past versions.

Even if prepare complex options, only a small percentage of people will use it.
What needs to be done is not to provide complex options, but to fix the current unintuitive Interval settings.

**Comment by hitsub** [comment]
This function is not easy to understand, but it is closed because of its low priority.
